services:
  fast-api:
    image: astral/uv:python3.13-bookworm
    container_name: fast-api
    working_dir: /app
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "80:8000"
    volumes:
      - "./:/app"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine3.22
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: >
      redis-server
      --save 60 10

volumes:
  redis_data: